<div class="block soap-icons">
<div class="row add-clearfix">
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-beach' ) !!} <i class="soap-icon-beach"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-juice' ) !!} <i class="soap-icon-juice"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-food' ) !!} <i class="soap-icon-food"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-fueltank' ) !!} <i class="soap-icon-fueltank"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-breakfast' ) !!} <i class="soap-icon-breakfast"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-fireplace' ) !!} <i class="soap-icon-fireplace"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-television' ) !!} <i class="soap-icon-television"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-fridge' ) !!} <i class="soap-icon-fridge"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-aircon' ) !!} <i class="soap-icon-aircon"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-fmstereo' ) !!} <i class="soap-icon-fmstereo"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-coffee' ) !!} <i class="soap-icon-coffee"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-party' ) !!} <i class="soap-icon-party"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-savings' ) !!} <i class="soap-icon-savings"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-address' ) !!} <i class="soap-icon-address"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-support' ) !!} <i class="soap-icon-support"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-tree' ) !!} <i class="soap-icon-tree"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-horn' ) !!} <i class="soap-icon-horn"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-winebar' ) !!} <i class="soap-icon-winebar"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-conference' ) !!} <i class="soap-icon-conference"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-friends' ) !!} <i class="soap-icon-friends"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-locations' ) !!} <i class="soap-icon-locations"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-couples' ) !!} <i class="soap-icon-couples"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-fitnessfacility' ) !!} <i class="soap-icon-fitnessfacility"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-plans' ) !!} <i class="soap-icon-plans"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-flightd' ) !!} <i class="soap-icon-flightd"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-key' ) !!} <i class="soap-icon-key"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-fork' ) !!} <i class="soap-icon-fork"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-guideline' ) !!} <i class="soap-icon-guideline"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-binoculars' ) !!} <i class="soap-icon-binoculars"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-wifi' ) !!} <i class="soap-icon-wifi"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-anchor' ) !!} <i class="soap-icon-anchor"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-joystick' ) !!} <i class="soap-icon-joystick"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-flexible' ) !!} <i class="soap-icon-flexible"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-phone' ) !!} <i class="soap-icon-phone"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-lost-found' ) !!} <i class="soap-icon-lost-found"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-securevault' ) !!} <i class="soap-icon-securevault"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-cruise-1' ) !!} <i class="soap-icon-cruise-1"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-cruise-2' ) !!} <i class="soap-icon-cruise-2"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-cruise' ) !!} <i class="soap-icon-cruise"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-cruise-3' ) !!} <i class="soap-icon-cruise-3"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-plane' ) !!} <i class="soap-icon-plane"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-plane-bottom' ) !!} <i class="soap-icon-plane-bottom"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-plane-left' ) !!} <i class="soap-icon-plane-left"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-plane-right' ) !!} <i class="soap-icon-plane-right"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-flight' ) !!} <i class="soap-icon-flight"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-pickanddrop' ) !!} <i class="soap-icon-pickanddrop"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-flight-1' ) !!} <i class="soap-icon-flight-1"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-flight-2' ) !!} <i class="soap-icon-flight-2"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-hotel-1' ) !!} <i class="soap-icon-hotel-1"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-hotel-2' ) !!} <i class="soap-icon-hotel-2"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-hotel-3' ) !!} <i class="soap-icon-hotel-3"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-hotel' ) !!} <i class="soap-icon-hotel"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-trunk-1' ) !!} <i class="soap-icon-trunk-1"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-trunk-2' ) !!} <i class="soap-icon-trunk-2"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-trunk-3' ) !!} <i class="soap-icon-trunk-3"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-flightryon' ) !!} <i class="soap-icon-flightryon"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-suitcase' ) !!} <i class="soap-icon-suitcase"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-baggage' ) !!} <i class="soap-icon-baggage"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-bag' ) !!} <i class="soap-icon-bag"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-businessbag' ) !!} <i class="soap-icon-businessbag"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-magazine' ) !!} <i class="soap-icon-magazine"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-slider-1' ) !!} <i class="soap-icon-slider-1"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-magazine-1' ) !!} <i class="soap-icon-magazine-1"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-slider' ) !!} <i class="soap-icon-slider"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-baggage-status' ) !!} <i class="soap-icon-baggage-status"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-baggage-1' ) !!} <i class="soap-icon-baggage-1"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-baggage-2' ) !!} <i class="soap-icon-baggage-2"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-baggage-3' ) !!} <i class="soap-icon-baggage-3"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-damaged-baggage' ) !!} <i class="soap-icon-damaged-baggage"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-delayed-baggage' ) !!} <i class="soap-icon-delayed-baggage"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-baggage-4' ) !!} <i class="soap-icon-baggage-4"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-baggage-5' ) !!} <i class="soap-icon-baggage-5"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-shopping' ) !!} <i class="soap-icon-shopping"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-shopping-1' ) !!} <i class="soap-icon-shopping-1"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-shopping-2' ) !!} <i class="soap-icon-shopping-2"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-shopping-3' ) !!} <i class="soap-icon-shopping-3"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-camera-1' ) !!} <i class="soap-icon-camera-1"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-camera-2' ) !!} <i class="soap-icon-camera-2"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-photogallery' ) !!} <i class="soap-icon-photogallery"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-camera-3' ) !!} <i class="soap-icon-camera-3"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-balloon' ) !!} <i class="soap-icon-balloon"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-globe' ) !!} <i class="soap-icon-globe"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-places' ) !!} <i class="soap-icon-places"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-clock-1' ) !!} <i class="soap-icon-clock-1"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-clock' ) !!} <i class="soap-icon-clock"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-settings' ) !!} <i class="soap-icon-settings"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-settings-1' ) !!} <i class="soap-icon-settings-1"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-bad' ) !!} <i class="soap-icon-bad"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-recommend' ) !!} <i class="soap-icon-recommend"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-entertainment' ) !!} <i class="soap-icon-entertainment"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-departure' ) !!} <i class="soap-icon-departure"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-letter' ) !!} <i class="soap-icon-letter"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-message' ) !!} <i class="soap-icon-message"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-search-plus' ) !!} <i class="soap-icon-search-plus"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-search-minus' ) !!} <i class="soap-icon-search-minus"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-search' ) !!} <i class="soap-icon-search"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-automatic' ) !!} <i class="soap-icon-automatic"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-parking' ) !!} <i class="soap-icon-parking"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-status' ) !!} <i class="soap-icon-status"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-restricted' ) !!} <i class="soap-icon-restricted"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-insurance' ) !!} <i class="soap-icon-insurance"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-doc-minus' ) !!} <i class="soap-icon-doc-minus"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-doc-plus' ) !!} <i class="soap-icon-doc-plus"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-liability' ) !!} <i class="soap-icon-liability"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-stories' ) !!} <i class="soap-icon-stories"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-calendar' ) !!} <i class="soap-icon-calendar"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-availability' ) !!} <i class="soap-icon-availability"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-calendar-1' ) !!} <i class="soap-icon-calendar-1"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-calendar-check' ) !!} <i class="soap-icon-calendar-check"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-list' ) !!} <i class="soap-icon-list"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-grid' ) !!} <i class="soap-icon-grid"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-block' ) !!} <i class="soap-icon-block"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-letter-1' ) !!} <i class="soap-icon-letter-1"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-heart' ) !!} <i class="soap-icon-heart"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-star-1' ) !!} <i class="soap-icon-star-1"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-wishlist' ) !!} <i class="soap-icon-wishlist"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-star' ) !!} <i class="soap-icon-star"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-left' ) !!} <i class="soap-icon-left"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-right' ) !!} <i class="soap-icon-right"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-top' ) !!} <i class="soap-icon-top"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-bottom' ) !!} <i class="soap-icon-bottom"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-arrow-bottom' ) !!} <i class="soap-icon-arrow-bottom"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-arrow-top' ) !!} <i class="soap-icon-arrow-top"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-arrow-right' ) !!} <i class="soap-icon-arrow-right"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-arrow-left' ) !!} <i class="soap-icon-arrow-left"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-roundtriangle-left' ) !!} <i class="soap-icon-roundtriangle-left"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-roundtriangle-right' ) !!} <i class="soap-icon-roundtriangle-right"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-roundtriangle-top' ) !!} <i class="soap-icon-roundtriangle-top"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-roundtriangle-bottom' ) !!} <i class="soap-icon-roundtriangle-bottom"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-chevron-left' ) !!} <i class="soap-icon-chevron-left"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-chevron-right' ) !!} <i class="soap-icon-chevron-right"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-chevron-top' ) !!} <i class="soap-icon-chevron-top"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-chevron-down' ) !!} <i class="soap-icon-chevron-down"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-longarrow-left' ) !!} <i class="soap-icon-longarrow-left"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-longarrow-right' ) !!} <i class="soap-icon-longarrow-right"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-longarrow-up' ) !!} <i class="soap-icon-longarrow-up"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-longarrow-bottom' ) !!} <i class="soap-icon-longarrow-bottom"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-triangle-left' ) !!} <i class="soap-icon-triangle-left"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-triangle-right' ) !!} <i class="soap-icon-triangle-right"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-triangle-top' ) !!} <i class="soap-icon-triangle-top"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-triangle-bottom' ) !!} <i class="soap-icon-triangle-bottom"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-check-1' ) !!} <i class="soap-icon-check-1"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-close' ) !!} <i class="soap-icon-close"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-plus' ) !!} <i class="soap-icon-plus"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-minus' ) !!} <i class="soap-icon-minus"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-features' ) !!} <i class="soap-icon-features"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-passed' ) !!} <i class="soap-icon-passed"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-passenger' ) !!} <i class="soap-icon-passenger"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-ski' ) !!} <i class="soap-icon-ski"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-handicapaccessiable' ) !!} <i class="soap-icon-handicapaccessiable"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-swimming' ) !!} <i class="soap-icon-swimming"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-man-1' ) !!} <i class="soap-icon-man-1"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-man-2' ) !!} <i class="soap-icon-man-2"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-man-3' ) !!} <i class="soap-icon-man-3"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-dog' ) !!} <i class="soap-icon-dog"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-adventure' ) !!} <i class="soap-icon-adventure"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-comfort' ) !!} <i class="soap-icon-comfort"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-playplace' ) !!} <i class="soap-icon-playplace"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-smoking' ) !!} <i class="soap-icon-smoking"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-doorman' ) !!} <i class="soap-icon-doorman"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-elevator' ) !!} <i class="soap-icon-elevator"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-tub' ) !!} <i class="soap-icon-tub"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-apple' ) !!} <i class="soap-icon-apple"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-googleplay' ) !!} <i class="soap-icon-googleplay"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-twitter' ) !!} <i class="soap-icon-twitter"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-facebook' ) !!} <i class="soap-icon-facebook"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-googleplus' ) !!} <i class="soap-icon-googleplus"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-pinterest' ) !!} <i class="soap-icon-pinterest"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-vimeo' ) !!} <i class="soap-icon-vimeo"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-flickr' ) !!} <i class="soap-icon-flickr"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-soundcloud' ) !!} <i class="soap-icon-soundcloud"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-stumbleupon' ) !!} <i class="soap-icon-stumbleupon"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-linkedin' ) !!} <i class="soap-icon-linkedin"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-dribble' ) !!} <i class="soap-icon-dribble"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-behance' ) !!} <i class="soap-icon-behance"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-deviantart' ) !!} <i class="soap-icon-deviantart"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-myspace' ) !!} <i class="soap-icon-myspace"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-youtube' ) !!} <i class="soap-icon-youtube"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-tumblr' ) !!} <i class="soap-icon-tumblr"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-instagram' ) !!} <i class="soap-icon-instagram"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-skype' ) !!} <i class="soap-icon-skype"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-envato' ) !!} <i class="soap-icon-envato"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-user' ) !!} <i class="soap-icon-user"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-pets' ) !!} <i class="soap-icon-pets"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-family' ) !!} <i class="soap-icon-family"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-check' ) !!} <i class="soap-icon-check"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-generalmessage' ) !!} <i class="soap-icon-generalmessage"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-notice' ) !!} <i class="soap-icon-notice"></i></label></div>
    <div class="radio col-xs-4 col-sm-3 col-md-2"><label class="radio-inline ">{!! Form::radio('icon', 'soap-icon-error' ) !!} <i class="soap-icon-error"></i></label></div>
</div>
</div>